#------------------------------------------------------------------
# We group observables into blocks according to type of observable
# for convenience, e.g. {type}: {observable}_{experiment}
#
# For each observable, we include its specific cuts in its block
#
# In the analysis code, we will store observables in a dictionary,
# labeled as: {type}_{observable}_{experiment}_{suffix}
# For example: hadron_pt_cms
#              jet_mass_alice_R0.2
# where the optional suffix is only present when needed. 
#
# We compute each observable only if it lies in the specified centrality range.
# We include all available centralities up to 50% centrality, at present.
#
# We include hepdata file paths when appropriate (relative to JETSCAPE-analysis directory),
# to be used for histogram binning (via hepdata histogram) and plotting (via hepdata tgraph).
# Note that the pp hepdata files contain distributions, while the AA hepdata files contain RAA ratios.
# Note that we bin pp observables according to the binning in each AA centrality;
# the pp hepdata tgraphs are included only for QA.
#------------------------------------------------------------------
sqrt_s: 5020

# General jet finding parameters
jet_R: [0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0]
min_jet_pt: 20.
max_jet_y: 3.

# General grooming parameters
SoftDrop:
  - {'zcut': 0.1, 'beta': 0}
  - {'zcut': 0.2, 'beta': 0}
  - {'zcut': 0.4, 'beta': 0}
  - {'zcut': 0.5, 'beta': 1.5}
#------------------------------------------------------------------
#------------------------------------------------------------------
# Hadron spectra
# Unless otherwise noted: Primary charged particles (w/ mean proper lifetime Ï„ larger than 1 cm/c )
hadron:

  # https://www.hepdata.net/record/ins1657384
  pt_ch_alice:
    eta_cut: 0.8
    pt: [5.0, 50.]
    centrality: [[0,5], [5,10], [10,20], [20,30], [30,40], [40,50]]
    xtitle: '#it{p}_{T} (GeV/#it{c})'
    logy: True
    
    hepdata: 'HEPData-ins1657384-v1-root.root'
    hepdata_pp_dir: 'Table 4'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{1}{#it{N}_{event}} #frac{d^{2}#it{N}}{d#it{p}_{T}d#it{#eta}} #left[(GeV/c)^{-1}#right]'
    y_min_pp: 2e-8
    y_max_pp: 1e4
    
    hepdata_AA_dir: 'Table 8'
    hepdata_AA_gname: ['Graph1D_y1', 'Graph1D_y2', 'Graph1D_y3', 'Graph1D_y4', 'Graph1D_y5', 'Graph1D_y6']
    hepdata_AA_hname: ['Hist1D_y1', 'Hist1D_y2', 'Hist1D_y3', 'Hist1D_y4', 'Hist1D_y5', 'Hist1D_y6']
    ytitle: '#it{R}_{AA}'
  
  # https://www.hepdata.net/record/ins1759506 -- charged pions
  pt_pi_alice:
    eta_cut: 0.8
    pt: [5.0, 20.]
    centrality: [[0,5], [5,10], [10,20], [20,30], [30,40], [40,50]]
    xtitle: '#it{p}_{T}'
    logy: True
    
    hepdata: 'HEPData-ins1759506-v1-root.root'
    hepdata_pp_dir: 'Table 2'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{1}{#it{N}_{event}} #frac{d^{2}#it{N}}{d#it{p}_{T}d#it{#eta}} #left[(GeV/c)^{-1}#right]'
    y_min_pp: 2e-8
    y_max_pp: 1e4
    
    hepdata_AA_dir: 'Table 15'
    hepdata_AA_gname: ['Graph1D_y1', 'Graph1D_y2', 'Graph1D_y3', 'Graph1D_y7', 'Graph1D_y8', 'Graph1D_y9']
    hepdata_AA_hname: ['Hist1D_y1', 'Hist1D_y2', 'Hist1D_y3', 'Hist1D_y7', 'Hist1D_y8', 'Hist1D_y9']
    ytitle: '#it{R}_{AA}'

  # https://www.hepdata.net/record/ins1496050
  pt_ch_cms:
    eta_cut: 1.0
    pt: [5.0, 400.]
    centrality: [[0,5], [5,10], [10,30], [30,50]]
    xtitle: '#it{p}_{T}'
    logy: True
    
    hepdata: 'HEPData-ins1496050-v2-root.root'
    hepdata_pp_dir: 'Table 7'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{1}{#it{N}_{event}} E #frac{d^{2}#it{N}}{d#it{p}_{T}d#it{#eta}} #left[(GeV/c)^{-1}#right]'
    y_min_pp: 2e-8
    y_max_pp: 1e4
    
    hepdata_AA_dir: ['Table 8', 'Table 9', 'Table 10', 'Table 11']
    hepdata_AA_gname: 'Graph1D_y1'
    hepdata_AA_hname: 'Hist1D_y1'
    ytitle: '#it{R}_{AA}'
#------------------------------------------------------------------
#------------------------------------------------------------------
# Hadron correlations
hadron_correlations:

  # https://www.hepdata.net/record/ins1686834
  v2_atlas:
    eta_cut: 2.5
    pt: [5., 60.]
  
  # https://www.hepdata.net/record/ins1511868
  v2_cms:
    pt: [5., 100.]
#------------------------------------------------------------------
#------------------------------------------------------------------
# Inclusive jet observables -- full jets
inclusive_jet:

  # https://www.hepdata.net/record/ins1755387
  # Note: pT^{ch lead} > 5,7 GeV (for R=0.2,0.4)
  # Note that results are reported both with and without the pT,lead cut on the pp jet cross-section
  # Here, we use the result where the cut is applied on PbPb and pp
  # Note: The pp HEPData file contains no leading track requirement (only used for QA)
  pt_alice:
    jet_R: [0.2, 0.4]
    eta_cut_R: 0.7
    pt: [40., 140.]
    centrality: [[0,10]]
    xtitle: '#it{p}_{T,jet} (GeV/#it{c})'
    logy: True
    
    hepdata: 'HEPData-ins1755387-v1-root.root'
    hepdata_pp_R0.2_dir: 'Table 2'
    hepdata_pp_R0.4_dir: 'Table 4'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{d^{2}#sigma}{d#it{p}_{T}d#it{#eta}} #left[mb/(GeV/c)^{-1}#right]'
    y_min_pp: 2e-8
    y_max_pp: 1e-1
    
    hepdata_AA_R0.2_dir: ['Table 30']
    hepdata_AA_R0.4_dir: ['Table 31']
    hepdata_AA_gname: 'Graph1D_y1'
    hepdata_AA_hname: 'Hist1D_y1'
    ytitle: '#it{R}_{AA}'

  # https://www.hepdata.net/record/ins1673184
  # Note: Two charged tracks with pt>4 GeV are required in Pb-Pb
  #       (they argue this is small...unclear if they correct for it...we will ignore it here)
  # Note: The paper also performs rapidity dependence for 0-10%, which we omit for now
  pt_atlas:
    jet_R: [0.4]
    y_cut: 2.8
    pt: [50., 1000.]
    centrality: [[0,10], [10,20], [20,30], [30,40], [40,50]]
    xtitle: '#it{p}_{T,jet} (GeV/#it{c})'
    logy: True

    hepdata: 'HEPData-ins1673184-v1-root.root'
    hepdata_pp_R0.4_dir: 'Table 4'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{d^{2}#sigma}{d#it{p}_{T}d#it{#eta}} #left[mb/(GeV/c)^{-1}#right]'
    y_min_pp: 2e-8
    y_max_pp: 1e-1
    
    hepdata_AA_R0.4_dir: ['Table 19', 'Table 20', 'Table 21', 'Table 22', 'Table 23']
    hepdata_AA_gname: 'Graph1D_y1'
    hepdata_AA_hname: 'Hist1D_y1'
    ytitle: '#it{R}_{AA}'
    
  # https://www.hepdata.net/record/ins1848440
  pt_cms:
    jet_R: [0.2, 0.3, 0.4, 0.6, 0.8, 1.0]
    eta_cut: 2.0
    pt: [200., 1000.]
    centrality: [[0,10], [10,30], [30,50]]
    xtitle: '#it{p}_{T,jet} (GeV/#it{c})'
    logy: True

    hepdata: 'HEPData-ins1848440-v1-root.root'
    hepdata_pp_R0.2_dir: 'Figure 5-1'
    hepdata_pp_R0.3_dir: 'Figure 5-2'
    hepdata_pp_R0.4_dir: 'Figure 5-3'
    hepdata_pp_R0.6_dir: 'Figure 5-4'
    hepdata_pp_R0.8_dir: 'Figure 5-5'
    hepdata_pp_R1.0_dir: 'Figure 5-6'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{d^{2}#sigma}{d#it{p}_{T}d#it{#eta}} #left[mb/(GeV/c)^{-1}#right]'
    y_min_pp: 2e-8
    y_max_pp: 1e-1
    
    hepdata_AA_R0.2_dir: 'Figure 7-1'
    hepdata_AA_R0.3_dir: 'Figure 7-2'
    hepdata_AA_R0.4_dir: 'Figure 7-3'
    hepdata_AA_R0.6_dir: 'Figure 7-4'
    hepdata_AA_R0.8_dir: 'Figure 7-5'
    hepdata_AA_R1.0_dir: 'Figure 7-6'
    hepdata_AA_gname: ['Graph1D_y1', 'Graph1D_y2', 'Graph1D_y3']
    hepdata_AA_hname: ['Hist1D_y1', 'Hist1D_y2', 'Hist1D_y3']
    ytitle: '#it{R}_{AA}'

  # https://www.hepdata.net/record/ins1673177
  Dz_atlas:
    jet_R: [0.4]
    y_cut: 2.1
    pt: [126., 158.49, 199.53, 251.19, 316.22, 398.1]
    centrality: [[0,10], [10,20], [20,30], [30,40]]
    xtitle: '#it{p}_{T,jet} (GeV/#it{c})'
    
    hepdata: 'HEPData-ins1673177-v2-root.root'
    hepdata_pp_R0.4_pt0_dir: 'Table 0'
    hepdata_pp_R0.4_pt1_dir: 'Table 4'
    hepdata_pp_R0.4_pt2_dir: 'Table 8'
    hepdata_pp_R0.4_pt3_dir: 'Table 12'
    hepdata_pp_R0.4_pt4_dir: 'Table 16'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{d^{2}#sigma}{d#it{p}_{T}d#it{#eta}} #left[mb/(GeV/c)^{-1}#right]'
    y_min_pp: 2e-8
    y_max_pp: 1e-1
    
    hepdata_AA_R0.4_pt0_dir: 'Table 2'
    hepdata_AA_R0.4_pt1_dir: 'Table 6'
    hepdata_AA_R0.4_pt2_dir: 'Table 10'
    hepdata_AA_R0.4_pt3_dir: 'Table 14'
    hepdata_AA_R0.4_pt4_dir: 'Table 18'
    hepdata_AA_gname: ['Graph1D_y1', 'Graph1D_y2', 'Graph1D_y3', 'Graph1D_y4']
    hepdata_AA_hname: ['Hist1D_y1', 'Hist1D_y2', 'Hist1D_y3', 'Hist1D_y4']
    ytitle: '#it{R}_{D(z)}'
    
  Dpt_atlas:
    jet_R: [0.4]
    y_cut: 2.1
    pt: [126., 158.49, 199.53, 251.19, 316.22, 398.1]
    centrality: [[0,10], [10,20], [20,30], [30,40]]
    xtitle: '#it{p}_{T,jet} (GeV/#it{c})'
    
    hepdata: 'HEPData-ins1673177-v2-root.root'
    hepdata_pp_R0.4_pt0_dir: 'Table 1'
    hepdata_pp_R0.4_pt1_dir: 'Table 5'
    hepdata_pp_R0.4_pt2_dir: 'Table 9'
    hepdata_pp_R0.4_pt3_dir: 'Table 13'
    hepdata_pp_R0.4_pt4_dir: 'Table 17'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{d^{2}#sigma}{d#it{p}_{T}d#it{#eta}} #left[mb/(GeV/c)^{-1}#right]'
    y_min_pp: 2e-8
    y_max_pp: 1e-1
    
    hepdata_AA_R0.4_pt0_dir: 'Table 3'
    hepdata_AA_R0.4_pt1_dir: 'Table 7'
    hepdata_AA_R0.4_pt2_dir: 'Table 11'
    hepdata_AA_R0.4_pt3_dir: 'Table 15'
    hepdata_AA_R0.4_pt4_dir: 'Table 19'
    hepdata_AA_gname: ['Graph1D_y1', 'Graph1D_y2', 'Graph1D_y3', 'Graph1D_y4']
    hepdata_AA_hname: ['Hist1D_y1', 'Hist1D_y2', 'Hist1D_y3', 'Hist1D_y4']
    ytitle: '#it{R}_{D(pt)}'
  
  # https://www.hepdata.net/record/ins1789224
  charge_cms:
    jet_R: [0.4]
    eta_cut: 1.5
    pt_min: 120.
    centrality: [[0,10], [10,30], [30,50]]
    xtitle: 'Q'
    track_pt_min: 1.
    kappa: [0.3, 0.5, 0.7]
    
    hepdata: 'HEPData-ins1789224-v1-root.root'
    hepdata_pp_R0.4_kappa0.3_dir: 'Table 8'
    hepdata_pp_R0.4_kappa0.5_dir: 'Table 1'
    hepdata_pp_R0.4_kappa0.7_dir: 'Table 9'
    hepdata_pp_gname: 'Graph1D_y5'
    ytitle_pp: '#frac{d^{2}#sigma}{d#it{p}_{T}d#it{#eta}} #left[mb/(GeV/c)^{-1}#right]'
    y_min_pp: 2e-8
    y_max_pp: 1e-1
    
    hepdata_AA_R0.4_kappa0.3_dir: 'Table 8'
    hepdata_AA_R0.4_kappa0.5_dir: 'Table 1'
    hepdata_AA_R0.4_kappa0.7_dir: 'Table 9'
    hepdata_AA_gname: ['Graph1D_y1', 'Graph1D_y2', 'Graph1D_y3']
    hepdata_AA_hname: ['Hist1D_y1', 'Hist1D_y2', 'Hist1D_y3']
    ytitle: '#it{R}_{AA}'
    
  # https://www.hepdata.net/record/ins1672962
  mg_cms:
    jet_R: [0.4]
    eta_cut: 1.3
    pt: [140., 160., 180., 200., 300.]
    centrality: [[0,10], [10,30], [30,50]]
    dR: 0.1
    SoftDrop:
      - {'zcut': 0.1, 'beta': 0}
      - {'zcut': 0.5, 'beta': 1.5}
    xtitle: '#it{m}_{g}/#it{p}_{T,jet}'
    
    hepdata: 'HEPData-ins1672962-v1-root.root'
    hepdata_pp_R0.4_zcut0.1_beta0_dir: 'Figure 2a'
    hepdata_pp_R0.4_zcut0.5_beta1.5_dir: 'Figure 2b'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{d^{2}#sigma}{d#it{p}_{T}d#it{#eta}} #left[mb/(GeV/c)^{-1}#right]'
    y_min_pp: 0.
    y_max_pp: 25
    
    hepdata_pp_R0.4_zcut0.1_beta0_pt0_dir: 'Figure 5b'
    hepdata_pp_R0.4_zcut0.5_beta1.5_pt0_dir: 'Figure 6b'
    hepdata_AA_gname_pt0: ['Graph1D_y1']
    hepdata_AA_hname_pt0: ['Hist1D_y1']
    hepdata_pp_R0.4_zcut0.1_beta0_pt1_dir: 'Figure 3b'
    hepdata_pp_R0.4_zcut0.5_beta1.5_pt1_dir: 'Figure 4b'
    hepdata_AA_gname_pt1: ['Graph1D_y1', 'Graph1D_y2', 'Graph1D_y3']
    hepdata_AA_hname_pt1: ['Hist1D_y1', 'Hist1D_y2', 'Hist1D_y3']
    hepdata_pp_R0.4_zcut0.1_beta0_pt2_dir: 'Figure 5b'
    hepdata_pp_R0.4_zcut0.5_beta1.5_pt2_dir: 'Figure 6b'
    hepdata_AA_gname_pt2: ['Graph1D_y3']
    hepdata_AA_hname_pt2: ['Hist1D_y3']
    hepdata_pp_R0.4_zcut0.1_beta0_pt3_dir: 'Figure 5b'
    hepdata_pp_R0.4_zcut0.5_beta1.5_pt3_dir: 'Figure 6b'
    hepdata_AA_gname_pt3: ['Graph1D_y4']
    hepdata_AA_hname_pt3: ['Hist1D_y4']
    ytitle: 'PbPb / smeared pp'
    
  # https://www.hepdata.net/record/ins1620905
  zg_cms:
    jet_R: [0.4]
    eta_cut: 1.3
    pt: [140., 160., 180., 200., 250., 300., 500.]
    centrality: [[0,10], [10,30], [30,50]]
    dR: 0.1
    SoftDrop:
      - {'zcut': 0.1, 'beta': 0}
    xtitle: '#it{z}_{g}'

    hepdata: 'HEPData-ins1620905-v1-root.root'
    hepdata_pp_pt1_dir: 'Table 2'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{d^{2}#sigma}{d#it{p}_{T}d#it{#eta}} #left[mb/(GeV/c)^{-1}#right]'
    y_min_pp: 0.
    y_max_pp: 25
    
    hepdata_AA_pt0_dir: ['Figure 11']
    hepdata_AA_pt1_dir: ['Figure 10', 'Figure 9', 'Figure 8']
    hepdata_AA_pt2_dir: ['Figure 13']
    hepdata_AA_pt3_dir: ['Figure 14']
    hepdata_AA_pt4_dir: ['Figure 15']
    hepdata_AA_pt5_dir: ['Figure 16']
    hepdata_AA_gname: 'Graph1D_y1'
    hepdata_AA_hname: 'Hist1D_y1'
    
#------------------------------------------------------------------
#------------------------------------------------------------------
# Inclusive jet observables -- charged jets
inclusive_chjet:
  
  # ALICE-PUBLIC-2020-006 (no hepdata yet)
  # TODO: Update binnings
  zg_alice:
    jet_R: [0.2, 0.4]
    eta_cut_R: 0.9
    pt_ch: [60., 80.]
    centrality: [[0,10], [30,50]]
    bins: [0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
    SoftDrop:
      - {'zcut': 0.2, 'beta': 0}
  tg_alice:
    jet_R: [0.2, 0.4]
    eta_cut_R: 0.9
    pt_ch: [60., 80.]
    centrality: [[0,10], [30,50]]
    bins: [0., 0.1, 0.15, 0.22, 0.3, 0.4, 0.5, 0.7, 1.0]
    SoftDrop:
      - {'zcut': 0.2, 'beta': 0}
      - {'zcut': 0.4, 'beta': 0}
#------------------------------------------------------------------
