#------------------------------------------------------------------
# We group observables into blocks according to type of observable
# for convenience, e.g. {type}: {observable}_{experiment}
#
# For each observable, we include its specific cuts in its block
#
# In the analysis code, we will store observables in a dictionary,
# labeled as: {type}_{observable}_{experiment}_{suffix}
# For example: hadron_pt_cms
#              jet_mass_alice_R0.2
# where the optional suffix is only present when needed.
#
# We compute each observable only if it lies in the specified centrality range.
# We include all available centralities up to 50% centrality, at present.
#
# We include hepdata file paths when appropriate (relative to JETSCAPE-analysis directory),
# to be used for histogram binning (via hepdata histogram) and plotting (via hepdata tgraph).
# Note that the pp hepdata files contain distributions, while the AA hepdata files contain RAA ratios.
# Note that we bin pp observables according to the binning in each AA centrality;
# the pp hepdata tgraphs are included only for QA.
#------------------------------------------------------------------
sqrt_s: 2760

# General jet finding parameters
jet_R: [0.2, 0.3, 0.4, 0.5]
min_jet_pt: 20.
max_jet_y: 3.
#------------------------------------------------------------------
#------------------------------------------------------------------
# Hadron spectra
# Unless otherwise noted: Primary charged particles (w/ mean proper lifetime Ï„ larger than 1 cm/c )
hadron:

  # https://www.hepdata.net/record/ins1657384
  # Figs 3,6
  pt_ch_alice:
    eta_cut: 0.8
    pt: [5.0, 50.]
    centrality: [[0,5], [5,10], [10,20], [20,30], [30,40], [40,50]]
    xtitle: '#it{p}_{T} (GeV/#it{c})'
    logy: True
    
    hepdata: 'HEPData-ins1657384-v1-root.root'
    hepdata_pp_dir: 'Table 4'
    hepdata_pp_gname: 'Graph1D_y2'
    ytitle_pp: '#frac{1}{#it{N}_{event}} #frac{d^{2}#it{N}}{d#it{p}_{T}d#it{#eta}} #left[(GeV/c)^{-1}#right]'
    y_min_pp: 2e-9
    y_max_pp: 1e4
    
    hepdata_AA_dir: 'Table 7'
    hepdata_AA_gname: ['Graph1D_y1', 'Graph1D_y2', 'Graph1D_y3', 'Graph1D_y4', 'Graph1D_y5', 'Graph1D_y6']
    hepdata_AA_hname: ['Hist1D_y1', 'Hist1D_y2', 'Hist1D_y3', 'Hist1D_y4', 'Hist1D_y5', 'Hist1D_y6']
    ytitle: '#it{R}_{AA}'
    
  # https://www.hepdata.net/record/ins1377750 -- charged pions (no pp hepdata)
  # Figs 22,23
  pt_pi_alice:
    eta_cut: 0.8
    pt: [5.0, 20.]
    centrality: [[0,5], [5,10], [10,20], [20,40]]
    xtitle: '#it{p}_{T}'
    logy: True
    
    ytitle_pp: '#frac{d^{2}#it{#sigma}}{d#it{p}_{T}d#it{#eta}} #left[(GeV/c)^{-1} b#right]'
    y_min_pp: 2e-8
    y_max_pp: 1e-2
    
    hepdata: 'HEPData-ins1377750-v1-root.root'
    hepdata_AA_dir: ['Table 7', 'Table 8', 'Table 9', 'Table 10']
    hepdata_AA_gname: 'Graph1D_y1'
    hepdata_AA_hname: 'Hist1D_y1'
    ytitle: '#it{R}_{AA}'
    
  # https://www.hepdata.net/record/ins1662651 (no pp hepdata)
  # Note: By default, pi0 will be decayed by JETSCAPE...
  pt_pi0_alice:
    eta_cut: 0.7
    pt: [5.0, 20.]
    centrality: [[0,10], [20,50]]
    xtitle: '#it{p}_{T} (GeV/#it{c})'
    logy: True
    
    ytitle_pp: '#frac{d^{2}#it{#sigma}}{d#it{p}_{T}d#it{#eta}} #left[(GeV/c)^{-1} b#right]'
    y_min_pp: 2e-8
    y_max_pp: 1e-2
    
    hepdata: 'HEPData-ins1662651-v1-root.root'
    hepdata_AA_dir: ['Table 5', 'Table 6']
    hepdata_AA_gname: 'Graph1D_y1'
    hepdata_AA_hname: 'Hist1D_y1'
    ytitle: '#it{R}_{AA}'
    
  # https://www.hepdata.net/record/ins1360290
  # leptons from W/Z decays removed
  # Figs 10,13
  # Note: The paper also performs pseudorapidity dependence for 0-5%, which we omit for now (Fig 14)
  pt_ch_atlas:
    eta_cut: 2.
    pt: [5.0, 150.]
    centrality: [[0,5], [5,10], [10,20], [20,30], [30,40], [40,50]]
    xtitle: '#it{p}_{T} (GeV/#it{c})'
    logy: True
    
    hepdata: 'HEPData-ins1360290-v2-root.root'
    hepdata_pp_dir: 'Table 1'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{1}{2#pip_{T}} #frac{d^{2}#it{#sigma}}{d#it{p}_{T}d#it{#eta}} #left[mb GeV^{2}#right]'
    y_min_pp: 2e-8
    y_max_pp: 1e4
    scale_by: '1/pt'
    
    hepdata_AA_dir: ['Table 33', 'Table 34', 'Table 35', 'Table 36', 'Table 37', 'Table 38']
    hepdata_AA_gname: 'Graph1D_y1'
    hepdata_AA_hname: 'Hist1D_y1'
    ytitle: '#it{R}_{AA}'

  # https://www.hepdata.net/record/ins1088823
  # Figs 3a,5
  pt_ch_cms:
    eta_cut: 1.0
    pt: [6.0, 100.]
    centrality: [[0,5], [5,10], [10,30]]
    xtitle: '#it{p}_{T} (GeV/#it{c})'
    logy: True
    
    hepdata: 'HEPData-ins1088823-v1-root.root'
    hepdata_pp_dir: 'Table 1'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: 'E #frac{d^{3}#it{N}_{ch}}{d^{3}#it{p}} #left[GeV^{-2}c^{3}#right]'
    # Note: E d^3N/Dp^3 = 1/(2pi pt) d^2N/dptdy
    y_min_pp: 2e-16
    y_max_pp: 1e2
    scale_by: '1/pt'
    skip_pp_ratio: True # Note: pp binning is different than PbPb binnings, so ratio will not work
    
    hepdata_AA_dir: 'Table 5'
    hepdata_AA_gname: ['Graph1D_y1', 'Graph1D_y2', 'Graph1D_y3']
    hepdata_AA_hname: ['Hist1D_y1', 'Hist1D_y2', 'Hist1D_y3']
    ytitle: '#it{R}_{AA}'
#------------------------------------------------------------------
#------------------------------------------------------------------
# Hadron correlations
hadron_correlations:

  # https://www.hepdata.net/record/ins1483164
  # pi0-hadron correlations
  pi0_hadron_alice:
    pt_trig: [8., 16.]
    centrality: [[0,10]]
    
  # https://www.hepdata.net/record/ins1116150
  # v2
  v2_alice:
    eta_cut: 0.8
    pt: [5., 20.]
    centrality: [[0,10]]
#------------------------------------------------------------------
#------------------------------------------------------------------
# Inclusive jet observables -- full jets
inclusive_jet:

  # https://www.hepdata.net/record/ins1343112
  # pT^{ch lead} > 5 GeV
  pt_alice:
    jet_R: [0.2]
    eta_cut_R: 0.7
    pt: [30., 120.]
    centrality: [[0,10], [10,30]]
    xtitle: '#it{p}_{T,jet} (GeV/#it{c})'
    logy: True
    
    # Note that pp hepdata has different binning than PbPb hepdata
    hepdata: 'HEPData-ins1343112-v1-root.root'
    hepdata_pp_dir_R0.2: 'Table 2'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{1}{N_{event}} #frac{d^{2}N}{d#it{p}_{T}d#it{#eta}} #left[(GeV/c)^{-1}#right]'
    y_min_pp: 2e-10
    y_max_pp: 1e-3
    
    hepdata_AA_dir_R0.2: ['Table 6', 'Table 7']
    hepdata_AA_gname: 'Graph1D_y1'
    hepdata_AA_hname: 'Hist1D_y1'
    ytitle: '#it{R}_{AA}'
    
  # https://www.hepdata.net/record/ins1326911
  # Figs 1,3
  # Note: the paper also considers the rapidity dependence, which we omit here for now
  pt_atlas:
    jet_R: [0.4]
    y_cut: 2.1
    pt: [32., 500.]
    centrality: [[0,10], [10,20], [20,30], [30,40], [40,50]]
    xtitle: '#it{p}_{T,jet} (GeV/#it{c})'
    logy: True
    
    hepdata: 'HEPData-ins1326911-v1-root.root'
    hepdata_pp_dir_R0.4: 'Table 2'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{d^{2}#sigma}{d#it{p}_{T}d#it{#eta}} #left[nb/(GeV/c)^{-1}#right]'
    y_min_pp: 2e-6
    y_max_pp: 1e4
    
    hepdata_AA_dir_R0.4: ['Table 27', 'Table 28', 'Table 29', 'Table 30', 'Table 31']
    hepdata_AA_gname: 'Graph1D_y1'
    hepdata_AA_hname: 'Hist1D_y1'
    ytitle: '#it{R}_{AA}'
    
  # https://www.hepdata.net/record/ins1126965
  # We omit this for now, since we don't consider peripheral events
  #pt_rcp_atlas:
  #  jet_R: [0.2, 0.3, 0.4, 0.5]
  #  eta_cut: 2.1
  #  pt: [38., 210.]
  
  # https://www.hepdata.net/record/ins1487278
  # Figs 4,8
  pt_cms:
    jet_R: [0.2, 0.3, 0.4]
    eta_cut: 2.0
    pt: [70., 300.]
    centrality: [[0,5], [5,10], [10,30], [30,50]]
    xtitle: '#it{p}_{T,jet} (GeV/#it{c})'
    logy: True

    hepdata: 'HEPData-ins1487278-v1-root.root'
    hepdata_pp_dir_R0.2: 'Table 4'
    hepdata_pp_dir_R0.3: 'Table 4'
    hepdata_pp_dir_R0.4: 'Table 4'
    hepdata_pp_gname_R0.2: 'Graph1D_y1'
    hepdata_pp_gname_R0.3: 'Graph1D_y2'
    hepdata_pp_gname_R0.4: 'Graph1D_y3'
    ytitle_pp: '#frac{d^{2}#sigma}{d#it{p}_{T}d#it{#eta}} #left[nb/(GeV/c)^{-1}#right]'
    y_min_pp: 2e-10
    y_max_pp: 1e10
    skip_pp_ratio: True
    
    hepdata_AA_dir_R0.2: ['Table 8a', 'Table 8b', 'Table 8c', 'Table 8d']
    hepdata_AA_dir_R0.3: ['Table 8a', 'Table 8b', 'Table 8c', 'Table 8d']
    hepdata_AA_dir_R0.4: ['Table 8a', 'Table 8b', 'Table 8c', 'Table 8d']
    hepdata_AA_gname_R0.2: 'Graph1D_y1'
    hepdata_AA_gname_R0.3: 'Graph1D_y2'
    hepdata_AA_gname_R0.4: 'Graph1D_y3'
    hepdata_AA_hname_R0.2: 'Hist1D_y1'
    hepdata_AA_hname_R0.3: 'Hist1D_y2'
    hepdata_AA_hname_R0.4: 'Hist1D_y3'
    ytitle: '#it{R}_{AA}'

  # https://www.hepdata.net/record/ins1511869
  # Note: the paper also considers the rapidity dependence, which we omit here for now (Figs 4,5)
  # Figs 3,7
  Dz_atlas:
    jet_R: [0.4]
    y_cut: 2.1
    pt: [100., 126., 158., 398.]
    centrality: [[0,10], [20,30], [30,40]]
    xtitle: '#it{z}'
    logy: True
    
    hepdata: 'HEPData-ins1511869-v1-root.root'
    hepdata_pp_dir_R0.4: 'Table 5'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{1}{N_{jet}} #frac{dN_{ch}}{d#it{z}}'
    y_min_pp: 2e-3
    y_max_pp: 1e6
    
    hepdata_AA_dir_R0.4_pt0: ['Table 61', 'Table 62', 'Table 63']
    hepdata_AA_dir_R0.4_pt1: ['Table 65', 'Table 66', 'Table 67']
    hepdata_AA_dir_R0.4_pt2: ['Table 69', 'Table 70', 'Table 71']
    hepdata_AA_gname: 'Graph1D_y1'
    hepdata_AA_hname: 'Hist1D_y1'
    ytitle: '#it{R}_{D(z)}'
    
  # Figs 2,6
  Dpt_atlas:
    jet_R: [0.4]
    y_cut: 2.1
    pt: [100., 126., 158., 398.]
    centrality: [[0,10], [20,30], [30,40]]
    xtitle: '#it{p}_{T,track} (GeV/#it{c})'
    logy: True
    
    hepdata: 'HEPData-ins1511869-v1-root.root'
    hepdata_pp_dir_R0.4: 'Table 1'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{1}{N_{jet}} #frac{dN_{ch}}{d#it{p}_{T}} #left[(GeV/c)^{-1}#right]'
    y_min_pp: 2e-4
    y_max_pp: 1e4
    
    hepdata_AA_dir_R0.4_pt0: ['Table 45', 'Table 46', 'Table 47']
    hepdata_AA_dir_R0.4_pt1: ['Table 49', 'Table 50', 'Table 51']
    hepdata_AA_dir_R0.4_pt2: ['Table 53', 'Table 54', 'Table 55']
    hepdata_AA_gname: 'Graph1D_y1'
    hepdata_AA_hname: 'Hist1D_y1'
    ytitle: '#it{R}_{D(z)}'
    
  # https://inspirehep.net/literature/1299142 (no hepdata)
  # https://twiki.cern.ch/CMSPublic/HIN12013DataTables
  # Figs 2,3,4
  Dz_cms:
    jet_R: [0.3]
    eta_cut: [0.3, 2.]
    pt: [100., 120., 150., 300.]
    centrality: [[0,10], [10,30], [30,50]]
    track_pt_min: 1.
    xtitle: '#it{#xi} = ln(1/#it{z})'
    logy: True
    
    data_pp_R0.3_pt0: 'hin_12_013_data_2.txt'
    data_pp_R0.3_pt1: 'hin_12_013_data_3.txt'
    data_pp_R0.3_pt2: 'hin_12_013_data_4.txt'
    ytitle_pp: '#frac{1}{N_{jet}} #frac{dN_{track}}{d#it{#xi}}'
    y_min_pp: 2e-3
    y_max_pp: 1e2
    
    data_AA_R0.3_pt0: 'hin_12_013_data_2.txt'
    data_AA_R0.3_pt1: 'hin_12_013_data_3.txt'
    data_AA_R0.3_pt2: 'hin_12_013_data_4.txt'
    data_AA_gname: 'Graph1D_y1'
    data_AA_hname: 'Hist1D_y1'
    ytitle: '#it{R}_{D(z)}'
    
  # Figs 6,7,8
  Dpt_cms:
    jet_R: [0.3]
    eta_cut: [0.3, 2.]
    pt: [100., 120., 150., 300.]
    centrality: [[0,10], [10,30], [30,50]]
    track_pt_min: 1.
    xtitle: '#it{p}_{T,track} (GeV/#it{c})'
    logy: True
    
    data_pp_R0.3_pt0: 'hin_12_013_data_6.txt'
    data_pp_R0.3_pt1: 'hin_12_013_data_7.txt'
    data_pp_R0.3_pt2: 'hin_12_013_data_8.txt'
    ytitle_pp: '#frac{1}{N_{jet}} #frac{dN_{track}}{d#it{p}_{T}} #left[(GeV/c)^{-1}#right]'
    y_min_pp: 2e-3
    y_max_pp: 1e2
    
    data_AA_R0.3_pt0: 'hin_12_013_data_6.txt'
    data_AA_R0.3_pt1: 'hin_12_013_data_7.txt'
    data_AA_R0.3_pt2: 'hin_12_013_data_8.txt'
    data_AA_gname: 'Graph1D_y1'
    data_AA_hname: 'Hist1D_y1'
    ytitle: '#it{R}_{D(z)}'
#------------------------------------------------------------------
#------------------------------------------------------------------
# Inclusive jet observables -- charged jets
inclusive_chjet:

  # https://www.hepdata.net/record/ins1263194
  # Mostly this paper is RCP (no pp), which we omit for now -- however it has R02/R03 ratio for 0-10%
  pt_alice:
    jet_R: [0.2, 0.3]
    eta_cut: 0.5
    pt: [30., 110.]
    centrality: [[0,10]]
    leading_track_min_pt: 5.
    xtitle: '#it{p}_{T} (GeV/#it{c})'
    logy: True
    
    ytitle_pp: '#frac{d^{2}#sigma}{d#it{p}_{T}d#it{#eta}} #left[mb/(GeV/c)^{-1}#right]'
    y_min_pp: 2e-14
    y_max_pp: 1e-2
    
    hepdata: 'HEPData-ins1263194-v1-root.root'
    hepdata_AA_dir: 'Table 30'
    hepdata_AA_gname: ['Graph1D_y1']
    hepdata_AA_hname: ['Hist1D_y1']
    ytitle: '#it{R}_{0.2} / #it{R}_{0.3}'
    
  # https://www.hepdata.net/record/ins1512107 (tgraph only...no binning)
  # Fig 7
  # Note: reference is p-Pb, which we use as a proxy for pp
  # Note: PbPb/pPb ratio is missing from HEPData (Fig 8)
  mass_alice:
    jet_R: [0.4]
    eta_cut_R: 0.9
    pt: [60., 80., 100., 120.]
    centrality: [[0,10]]
    bins: [0., 2, 4, 6, 8, 10, 12, 14, 16, 18]
    xtitle: '#it{m}_{jet}'
    
    hepdata: 'HEPData-ins1512107-v1-root.root'
    hepdata_pp_dir_R0.4_pt0: 'Table 1'
    hepdata_pp_dir_R0.4_pt1: 'Table 2'
    hepdata_pp_dir_R0.4_pt2: 'Table 3'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{1}{#sigma} #frac{d#sigma}{d#it{m}} #left[GeV^{-2}#right]'
    y_min_pp: 1e-3
    y_max_pp: 0.3
    
    hepdata_AA_dir_R0.4_pt0: 'Table 4'
    hepdata_AA_dir_R0.4_pt1: 'Table 5'
    hepdata_AA_dir_R0.4_pt2: 'Table 6'
    hepdata_AA_gname: 'Graph1D_y1'
    hepdata_AA_hname: 'Hist1D_y1'
    ytitle: '#it{R}_{D(z)}'

  # https://www.hepdata.net/record/ins1682990
  # Note: reference is to PYTHIA
  g_alice:
    jet_R: [0.2]
    eta_cut_R: 0.9
    pt: [40., 60.]
    centrality: [[0,10]]
    xtitle: '#it{g}'

    hepdata: 'HEPData-ins1682990-v1-root.root'
    hepdata_pp_dir_R0.2: 'Table 10'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{1}{#sigma} #frac{d#sigma}{d#it{g}} #left[(GeV/c)^{-1}#right]'
    y_min_pp: 0.
    y_max_pp: 30.
    
    hepdata_AA_dir_R0.2: 'Table 11'
    hepdata_AA_gname: ['Graph1D_y1']
    hepdata_AA_hname: ['Hist1D_y1']
    ytitle: '#it{R}_{AA}'
    
  ptd_alice:
    jet_R: [0.2]
    eta_cut_R: 0.9
    pt: [40., 60.]
    centrality: [[0,10]]
    xtitle: '#it{p}_{T,D}'
    
    hepdata: 'HEPData-ins1682990-v1-root.root'
    hepdata_pp_dir_R0.2: 'Table 13'
    hepdata_pp_gname: 'Graph1D_y1'
    ytitle_pp: '#frac{1}{#sigma} #frac{d#sigma}{d#it{p}_{T}d} #left[(GeV/c)^{-2}#right]'
    y_min_pp: 0.
    y_max_pp: 5.
    
    hepdata_AA_dir_R0.2: 'Table 14'
    hepdata_AA_gname: ['Graph1D_y1']
    hepdata_AA_hname: ['Hist1D_y1']
    ytitle: '#it{R}_{AA}'
#------------------------------------------------------------------
#------------------------------------------------------------------
# Jet correlation observables
semi_inclusive_chjet:

  # https://www.hepdata.net/record/ins1376027
  # Note: reference is PYTHIA
  #   Cuts / Notes:
  #       - pi - dPhi < 0.6 for accepting recoil jets
  #       - |eta_jet| < 0.9 - R
  #       - Track pt > 0.15 (not corrected)
  # Fig 9,10
  IAA_alice:
    jet_R: [0.2, 0.4, 0.5]
    eta_cut_R: 0.9
    pt: [20., 100.]
    centrality: [[0,10]]
    hadron_eta_cut: 0.9
    low_trigger_range: [8, 9]
    high_trigger_range: [20, 50]
    c_ref: [0.99, 0.96, 0.93]
    xtitle: '#it{p}_{T,jet} (GeV/#it{c})'
    logy: True
    
    ytitle_pp: '#Delta_{recoil}'
    y_min_pp: 2e-8
    y_max_pp: 2.

    hepdata: 'HEPData-ins1376027-v1-root.root'
    hepdata_AA_dir_R0.2: 'Table 32'
    hepdata_AA_dir_R0.4: 'Table 33'
    hepdata_AA_dir_R0.5: 'Table 34'
    hepdata_AA_dir_R0.2_R0.4: 'Table 35'
    hepdata_AA_dir_R0.2_R0.5: 'Table 36'
    hepdata_AA_gname: ['Graph1D_y1']
    hepdata_AA_hname: ['Hist1D_y1']
    ytitle: '#it{R}_{AA}'
   
  # Fig 11
  # Note: HEPData is the distribution, not the ratio
  dphi_alice:
    jet_R: [0.4]
    eta_cut_R: 0.9
    pt: [40., 60.]
    centrality: [[0,10]]
    hadron_eta_cut: 0.9
    low_trigger_range: [8, 9]
    high_trigger_range: [20, 50]
    c_ref: [0.96]
    xtitle: '#Delta#varphi'
    
    ytitle_pp: '#Phi(#Delta#it{#varphi})'
    y_min_pp: 0.
    y_max_pp: 1.
    
    hepdata: 'HEPData-ins1376027-v1-root.root'
    hepdata_AA_dir_R0.4: 'Table 37'
    hepdata_AA_gname: ['Graph1D_y1']
    hepdata_AA_hname: ['Hist1D_y1']
    ytitle: '#it{R}_{AA}'
  
  # https://inspirehep.net/literature/1862792
  # (hepdata not yet published)
  #   Cuts / Notes:
  #       - pi - dPhi < 0.6 for accepting recoil jets
  #       - |eta_jet| < 0.9 - R
  # There is no pp reference at 2.76 TeV -- we consider only the Pb-Pb distribution
  # We consider only tau2/tau1 w/CA reclustering for now
  nsubjettiness_alice:
    jet_R: [0.4]
    pt: [40., 60.]
    centrality: [[0,10]]
    low_trigger_range: [8, 9]
    high_trigger_range: [15, 45]
    xtitle: '#frac{#tau_{2}}{#tau_{1}}'
    
    ytitle_pp: '#frac{1}{#sigma} #frac{d^{2}#sigma}{d#it{p}_{T}d#it{#eta}} #left[mb/(GeV/c)^{-1}#right]'
    y_min_pp: 1e-3
    y_max_pp: 2.

    hepdata: 'HEPData-1623946228-v1-frac{tau_{2}}{tau_{1}}_with_CA_reclustering_in_Pb-Pb.root'
    hepdata_AA_dir: 'frac{tau_{2}}{tau_{1}} with CA reclustering in Pb-Pb'
    hepdata_AA_gname: ['Graph1D_y1']
    hepdata_AA_hname: ['Hist1D_y1']
    ytitle: '#frac{d^{2}#sigma}{d#it{p}_{T}d#it{#eta}} #left[mb/(GeV/c)^{-1}#right]'
#------------------------------------------------------------------
#------------------------------------------------------------------
dijet:

  # https://www.hepdata.net/record/ins1394678
  v2_alice:
    jet_R: [0.2]
    eta_cut: 0.7
    pt: [20., 90.]
    centrality: [[0,10]]
  
  # https://www.hepdata.net/record/ins1240088
  v2_atlas:
    jet_R: [0.2]
    pt: [45., 160.]
    centrality: [[0,10]]
  
  # https://inspirehep.net/literature/1607896 (no hepdata...requested to Dennis/Laura)
  xj_atlas:
    jet_R: [0.3, 0.4]
    centrality: [[0,10], [10,20], [20,30], [30,40]]
    pt: [25., 79.]
    pt_leading_min: 79.
    pt_subleading_min: 25.
    eta_cut: 2.1
#------------------------------------------------------------------
